export default {
    url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/30',
    id: 165055865,
    html_url: 'https://github.com/AlecAivazis/a-test-repo/pull/30',
    diff_url: 'https://github.com/AlecAivazis/a-test-repo/pull/30.diff',
    patch_url: 'https://github.com/AlecAivazis/a-test-repo/pull/30.patch',
    issue_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/30',
    number: 30,
    state: 'closed',
    locked: false,
    title: 'asdf',
    user: {
        login: 'AlecAivazis',
        id: 916317,
        avatar_url: 'https://avatars1.githubusercontent.com/u/916317?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/AlecAivazis',
        html_url: 'https://github.com/AlecAivazis',
        followers_url: 'https://api.github.com/users/AlecAivazis/followers',
        following_url: 'https://api.github.com/users/AlecAivazis/following{/other_user}',
        gists_url: 'https://api.github.com/users/AlecAivazis/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/AlecAivazis/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/AlecAivazis/subscriptions',
        organizations_url: 'https://api.github.com/users/AlecAivazis/orgs',
        repos_url: 'https://api.github.com/users/AlecAivazis/repos',
        events_url: 'https://api.github.com/users/AlecAivazis/events{/privacy}',
        received_events_url: 'https://api.github.com/users/AlecAivazis/received_events',
        type: 'User',
        site_admin: false
    },
    body: 'fixes #1 ',
    created_at: '2018-01-25T08:27:29Z',
    updated_at: '2018-01-25T08:27:44Z',
    closed_at: '2018-01-25T08:27:44Z',
    merged_at: '2018-01-25T08:27:43Z',
    merge_commit_sha: '344a49a208d6f7278bb3ce14a423c2176b9d5e7e',
    assignee: null,
    assignees: [],
    requested_reviewers: [],
    requested_teams: [],
    milestone: null,
    commits_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/30/commits',
    review_comments_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/30/comments',
    review_comment_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/comments{/number}',
    comments_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/30/comments',
    statuses_url:
        'https://api.github.com/repos/AlecAivazis/a-test-repo/statuses/4f5fe03c325235c29f9ff89ecf66f7fc15a386bf',
    head: {
        label: 'AlecAivazis:foo',
        ref: 'foo',
        sha: '4f5fe03c325235c29f9ff89ecf66f7fc15a386bf',
        user: {
            login: 'AlecAivazis',
            id: 916317,
            avatar_url: 'https://avatars1.githubusercontent.com/u/916317?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/AlecAivazis',
            html_url: 'https://github.com/AlecAivazis',
            followers_url: 'https://api.github.com/users/AlecAivazis/followers',
            following_url: 'https://api.github.com/users/AlecAivazis/following{/other_user}',
            gists_url: 'https://api.github.com/users/AlecAivazis/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/AlecAivazis/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/AlecAivazis/subscriptions',
            organizations_url: 'https://api.github.com/users/AlecAivazis/orgs',
            repos_url: 'https://api.github.com/users/AlecAivazis/repos',
            events_url: 'https://api.github.com/users/AlecAivazis/events{/privacy}',
            received_events_url: 'https://api.github.com/users/AlecAivazis/received_events',
            type: 'User',
            site_admin: false
        },
        repo: {
            id: 116403683,
            name: 'a-test-repo',
            full_name: 'AlecAivazis/a-test-repo',
            owner: [Object],
            private: false,
            html_url: 'https://github.com/AlecAivazis/a-test-repo',
            description: 'a repo for me to test github integrations',
            fork: false,
            url: 'https://api.github.com/repos/AlecAivazis/a-test-repo',
            forks_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/forks',
            keys_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/keys{/key_id}',
            collaborators_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/collaborators{/collaborator}',
            teams_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/teams',
            hooks_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/hooks',
            issue_events_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/events{/number}',
            events_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/events',
            assignees_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/assignees{/user}',
            branches_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/branches{/branch}',
            tags_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/tags',
            blobs_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/blobs{/sha}',
            git_tags_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/tags{/sha}',
            git_refs_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/refs{/sha}',
            trees_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/trees{/sha}',
            statuses_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/statuses/{sha}',
            languages_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/languages',
            stargazers_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/stargazers',
            contributors_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/contributors',
            subscribers_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/subscribers',
            subscription_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/subscription',
            commits_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/commits{/sha}',
            git_commits_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/commits{/sha}',
            comments_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/comments{/number}',
            issue_comment_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/comments{/number}',
            contents_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/contents/{+path}',
            compare_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/compare/{base}...{head}',
            merges_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/merges',
            archive_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/{archive_format}{/ref}',
            downloads_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/downloads',
            issues_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues{/number}',
            pulls_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls{/number}',
            milestones_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/milestones{/number}',
            notifications_url:
                'https://api.github.com/repos/AlecAivazis/a-test-repo/notifications{?since,all,participating}',
            labels_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/labels{/name}',
            releases_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/releases{/id}',
            deployments_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/deployments',
            created_at: '2018-01-05T16:16:15Z',
            updated_at: '2018-01-05T16:16:15Z',
            pushed_at: '2018-01-25T08:27:43Z',
            git_url: 'git://github.com/AlecAivazis/a-test-repo.git',
            ssh_url: 'git@github.com:AlecAivazis/a-test-repo.git',
            clone_url: 'https://github.com/AlecAivazis/a-test-repo.git',
            svn_url: 'https://github.com/AlecAivazis/a-test-repo',
            homepage: null,
            size: 15,
            stargazers_count: 0,
            watchers_count: 0,
            language: null,
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 0,
            license: null,
            forks: 0,
            open_issues: 0,
            watchers: 0,
            default_branch: 'master'
        }
    },
    base: {
        label: 'AlecAivazis:master',
        ref: 'master',
        sha: 'f3d54d4a3886be22b537a10af9ca10be8d11d039',
        user: {
            login: 'AlecAivazis',
            id: 916317,
            avatar_url: 'https://avatars1.githubusercontent.com/u/916317?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/AlecAivazis',
            html_url: 'https://github.com/AlecAivazis',
            followers_url: 'https://api.github.com/users/AlecAivazis/followers',
            following_url: 'https://api.github.com/users/AlecAivazis/following{/other_user}',
            gists_url: 'https://api.github.com/users/AlecAivazis/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/AlecAivazis/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/AlecAivazis/subscriptions',
            organizations_url: 'https://api.github.com/users/AlecAivazis/orgs',
            repos_url: 'https://api.github.com/users/AlecAivazis/repos',
            events_url: 'https://api.github.com/users/AlecAivazis/events{/privacy}',
            received_events_url: 'https://api.github.com/users/AlecAivazis/received_events',
            type: 'User',
            site_admin: false
        },
        repo: {
            id: 116403683,
            name: 'a-test-repo',
            full_name: 'AlecAivazis/a-test-repo',
            owner: [Object],
            private: false,
            html_url: 'https://github.com/AlecAivazis/a-test-repo',
            description: 'a repo for me to test github integrations',
            fork: false,
            url: 'https://api.github.com/repos/AlecAivazis/a-test-repo',
            forks_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/forks',
            keys_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/keys{/key_id}',
            collaborators_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/collaborators{/collaborator}',
            teams_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/teams',
            hooks_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/hooks',
            issue_events_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/events{/number}',
            events_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/events',
            assignees_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/assignees{/user}',
            branches_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/branches{/branch}',
            tags_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/tags',
            blobs_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/blobs{/sha}',
            git_tags_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/tags{/sha}',
            git_refs_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/refs{/sha}',
            trees_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/trees{/sha}',
            statuses_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/statuses/{sha}',
            languages_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/languages',
            stargazers_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/stargazers',
            contributors_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/contributors',
            subscribers_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/subscribers',
            subscription_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/subscription',
            commits_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/commits{/sha}',
            git_commits_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/git/commits{/sha}',
            comments_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/comments{/number}',
            issue_comment_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/comments{/number}',
            contents_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/contents/{+path}',
            compare_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/compare/{base}...{head}',
            merges_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/merges',
            archive_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/{archive_format}{/ref}',
            downloads_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/downloads',
            issues_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues{/number}',
            pulls_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls{/number}',
            milestones_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/milestones{/number}',
            notifications_url:
                'https://api.github.com/repos/AlecAivazis/a-test-repo/notifications{?since,all,participating}',
            labels_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/labels{/name}',
            releases_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/releases{/id}',
            deployments_url: 'https://api.github.com/repos/AlecAivazis/a-test-repo/deployments',
            created_at: '2018-01-05T16:16:15Z',
            updated_at: '2018-01-05T16:16:15Z',
            pushed_at: '2018-01-25T08:27:43Z',
            git_url: 'git://github.com/AlecAivazis/a-test-repo.git',
            ssh_url: 'git@github.com:AlecAivazis/a-test-repo.git',
            clone_url: 'https://github.com/AlecAivazis/a-test-repo.git',
            svn_url: 'https://github.com/AlecAivazis/a-test-repo',
            homepage: null,
            size: 15,
            stargazers_count: 0,
            watchers_count: 0,
            language: null,
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 0,
            license: null,
            forks: 0,
            open_issues: 0,
            watchers: 0,
            default_branch: 'master'
        }
    },
    _links: {
        self: { href: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/30' },
        html: { href: 'https://github.com/AlecAivazis/a-test-repo/pull/30' },
        issue: { href: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/30' },
        comments: { href: 'https://api.github.com/repos/AlecAivazis/a-test-repo/issues/30/comments' },
        review_comments: { href: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/30/comments' },
        review_comment: { href: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/comments{/number}' },
        commits: { href: 'https://api.github.com/repos/AlecAivazis/a-test-repo/pulls/30/commits' },
        statuses: {
            href:
                'https://api.github.com/repos/AlecAivazis/a-test-repo/statuses/4f5fe03c325235c29f9ff89ecf66f7fc15a386bf'
        }
    },
    author_association: 'OWNER',
    merged: true,
    mergeable: null,
    rebaseable: null,
    mergeable_state: 'unknown',
    merged_by: {
        login: 'AlecAivazis',
        id: 916317,
        avatar_url: 'https://avatars1.githubusercontent.com/u/916317?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/AlecAivazis',
        html_url: 'https://github.com/AlecAivazis',
        followers_url: 'https://api.github.com/users/AlecAivazis/followers',
        following_url: 'https://api.github.com/users/AlecAivazis/following{/other_user}',
        gists_url: 'https://api.github.com/users/AlecAivazis/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/AlecAivazis/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/AlecAivazis/subscriptions',
        organizations_url: 'https://api.github.com/users/AlecAivazis/orgs',
        repos_url: 'https://api.github.com/users/AlecAivazis/repos',
        events_url: 'https://api.github.com/users/AlecAivazis/events{/privacy}',
        received_events_url: 'https://api.github.com/users/AlecAivazis/received_events',
        type: 'User',
        site_admin: false
    },
    comments: 0,
    review_comments: 0,
    maintainer_can_modify: false,
    commits: 1,
    additions: 1,
    deletions: 1,
    changed_files: 1
}
