# system setup
sudo: required
dist: trusty

# language setup
language: node_js
node_js:
  - "9"

# install dependencies
install:
  - npm i -g truffle
  - npm i

# command to run tests
script:
  - npm run contracts:compile
  - npm run contracts:test
  - npm run test:coverage:report
